// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6XJ7T3QfF_fjsfEn38g6KEO45t0xv0bg',
    appId: '1:473959689900:web:db01f96764533cc284b909',
    messagingSenderId: '473959689900',
    projectId: 'planify-e6409',
    authDomain: 'planify-e6409.firebaseapp.com',
    storageBucket: 'planify-e6409.firebasestorage.app',
    measurementId: 'G-HR6QX1TFE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMa9GgRypZ0yMVMpJq7HSYGROpMhQBqvM',
    appId: '1:473959689900:android:cbd3202c5309cc0c84b909',
    messagingSenderId: '473959689900',
    projectId: 'planify-e6409',
    storageBucket: 'planify-e6409.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBURvgtVX3X-HZ_6yB1_iiE6P9UtSNCNgs',
    appId: '1:473959689900:ios:a5ca8299c32aa69184b909',
    messagingSenderId: '473959689900',
    projectId: 'planify-e6409',
    storageBucket: 'planify-e6409.firebasestorage.app',
    iosBundleId: 'com.example.planifyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBURvgtVX3X-HZ_6yB1_iiE6P9UtSNCNgs',
    appId: '1:473959689900:ios:a5ca8299c32aa69184b909',
    messagingSenderId: '473959689900',
    projectId: 'planify-e6409',
    storageBucket: 'planify-e6409.firebasestorage.app',
    iosBundleId: 'com.example.planifyMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6XJ7T3QfF_fjsfEn38g6KEO45t0xv0bg',
    appId: '1:473959689900:web:0184c9b4172fdf4b84b909',
    messagingSenderId: '473959689900',
    projectId: 'planify-e6409',
    authDomain: 'planify-e6409.firebaseapp.com',
    storageBucket: 'planify-e6409.firebasestorage.app',
    measurementId: 'G-CCY4YW4BNH',
  );
}
